language: node_js
node_js:
- 8.11.4
env:
  global:
    secure: qAkjAes7VM/gjP2M0d4uU7CQPxPUGs4wzKMpkPICvPajva4nXUdkw2CB6Pqp0PgN1pDl7rHXQ8RgnXezTbpcsjxgPoWZQUzlcgxhnK+39kBrMiBIYvUs2Z1u0JwZOvV1BhA2fDyafko8ncK1AaH/Toxz5kiH1fLIebt+/Z0G1AAaaoKxxEs4FR6D3xCoxdzcgSrV7Cc09qGpj9bkZ3MoqCEh2qoo4YEl4pkxkAHbVgLjlXUcH5GEOOG+rCm8Bgb4bbh8AqH6TW0gM63s/rJVAeg1H3AVxoEcYjVAJ11kYMNaAXmKR58t2Hrbykz2JofhVRDHlR05McF/lAJ42qUk/n6A/FLkGih7BGxlGIAkHvPFBuqrUFLzfU+KKcqQSwX6eLfftxLCWKi3zNXLfBEzsLoSo/7iVgrC4Y7hmsu8PPonaSL3hvD4s4XVFqwdytimARXdmFOaLLlq5tfv6ULG48y/fxA4yClDz3d2KcodgH91ZbrPgZXIHJG+aEhOqDimj7YyB4L7xrdMsegXSYqH3tb2slAH9EMgYUL1Ym/6Wau16/ECiwqp8futaOjkKcqTk+or/JIMUCTLjRuREVxEewEEiV1xnDxxCaRcVP15Ojzi77Fgy1qFnJ9PK5eeE9bApYu0OkZgWu066snAPy30CBkHSZ5ABIVrEP/i14bGTdo=
